# Site settings
title: Bright Birthing
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Charlottesville's doula agency: individualized care with the support of a village.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brightbirthing.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Blog settings
name:         Bright Birthing Blog
description:  Bright Birthing's Blog
url:          http://brightbirthing.com/blog/
