---
title: Bright Birthing
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Bright Birthing's Blog
baseurl: ''
url: http://brightbirthing.com/blog/
markdown: kramdown
name: Bright Birthing Blog
